### ISSUE TITLE
Missing connections

### ISSUE THREAD

**Issue by AvoMMH** [ldd/react-tech-tree#2]
Hey there,
I like the concept behind your package.
I have the issue, that the connections between the nodes are invisible.
Do you have any tips how I can display them.

I have MaterialUi installed, is there an issue with the css colliding?

**Comment by ldd** [comment]
ummm now that I think about it, that is possible.

I'd first check if there is a connection at all. (with chrome/firefox debuggion tools)

If they are there, I'd then see if I can manually override the style of one of them.
Generally, connections use very generic classes that could probably collide with materialUI. 

Also, make sure to include the CSS of the project!
`react-tech-tree/dist/index.css`

```css
.Tree .Link {
  /* stuff goes here */
}
```

Finally, if you have the page somewhere, I can help you debug it.

Thanks for using this package and sorry for the slow reply!

**Comment by AvoMMH** [comment]
Okay, I figured out, that there are no connections, but I dont know why.

Here is my Code snippet:
```
const NodeTree= () => {
  const nodes = [
    [
      { id: "A0", name: "A0" },
      { id: "B0", name: "B0" },
    ],
    [
      { id: "A1", name: "A1" },
      { id: "B1", name: "B1" },
    ],
  ];
  const links = [
    { from: "A0", to: "B0" },
    { from: "B1", to: "B0" },
    { from: "A0", to: "B1" },
  ];

  return (
    <>
      <Tree
        id="tree"
        nodes={nodes}
        links={links}
        NodeElement={(node) => {
          return (
            <Button variant="contained" key={node.id}>
              {node.name}
            </Button>
          );
        }}
      />
    </>
  );
};

export default NodeTree;
```

**Comment by jakubriedl** [comment]
I ran into the same issue. It is caused by missing `id` attribute. (this code needs it https://github.com/ldd/react-tech-tree/blob/master/src/helpers/svgHelper.js#L14-L16)

So to fix it @AvoMMH just update your `NodeElement` component to have the id
```
        NodeElement={(node) => {
          return (
            <Button variant="contained" key={node.id} id={node.id}>
              {node.name}
            </Button>
          );
        }}
```

**Comment by ldd** [comment]
thanks for finding this! 
I think I've seen this error myself. 
I'll include it in the `README.md` as a required property.

**Comment by AvoMMH** [comment]
Thanks, that solved it.
Sorry for the late reply
