### ISSUE TITLE
React Hook useLayoutEffect has a missing dependency: 'repositionLinks'

### ISSUE THREAD

**Issue by hagunnoo** [ldd/react-tech-tree#3]
Hi, I built a text_tooltip tree. The tree is rendered correctly, but the code compiles with warnings, as shown below.

![Screenshot 2020-12-02 at 10 55 27](https://user-images.githubusercontent.com/72602334/100863746-e9f2c780-348c-11eb-9256-09ac181b27a8.png)

Here's my usePosition.js script:
```
import { useLayoutEffect, useRef, useState } from "react";
import { getNodeDOMPositions, simplePathMaker } from "../helpers/svgHelper";

const usePosition = ({ links = [], pathMaker = simplePathMaker } = {}) => {
  // we must use a reference since we need Node's DOM position
  // https://stackoverflow.com/a/55996413
  const ref = useRef();
  const [nodePositions, setNodePositions] = useState(links);
  const repositionLinks = () =>
    setNodePositions(
      getNodeDOMPositions(nodePositions, ref.current, pathMaker)
    );

  // make sure to reposition links on window resize
  // to make content responsive
  // https://gist.github.com/gaearon/cb5add26336003ed8c0004c4ba820eae
  useLayoutEffect(() => {
    repositionLinks();
    window.addEventListener("resize", repositionLinks);
    return () => window.removeEventListener("resize", repositionLinks);
  }, []);
  return { ref, nodePositions };
};

export default usePosition;
```
How do I modify the code to get rid of the warning? Simply adding repositionLinks to the dependency array actually crashes the React app with error 
`Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.`

**Comment by ldd** [comment]
Ah, good old react being react.
The gist of it, if I recall correctly:
wrap `repositionLinks` inside a `useCallback`:

```js
  const repositionLinks = useCallback(() =>
    setNodePositions(
      getNodeDOMPositions(nodePositions, ref.current, pathMaker)
    ),[]);
``` 

If that's not it, I'd say to ask in a react-focused forum. This is one of those things that takes a bit of time to get once you start using hooks. I hope that helps!

**Comment by hagunnoo** [comment]
It didn't fix the issue, but thanks for the help nevertheless. I'll ask in a react-focussed forum 👍

**Comment by ldd** [comment]
were you able to find a solution? If not, let me know!
